apiVersion: v1
kind: Service
metadata:
  name: csms-runtime
  labels:
    app.kubernetes.io/name: csms-runtime
spec:
  selector:
    app.kubernetes.io/name: csms-runtime
  ports:
    - name: http
      port: 8080
      targetPort: http
