apiVersion: v1
kind: Service
metadata:
  name: csms-redis
  labels:
    app.kubernetes.io/name: csms-redis
spec:
  selector:
    app.kubernetes.io/name: csms-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
